[workspace]
resolver = "2"
members = [
    "api",
    "ipfs",
    "sink",
    "substreams-utils",
    "web3-utils",
    "grc20-core",
    "grc20-macros",
    "grc20-sdk", "mcp-server", "ai-search",
]
