// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metadata {
    #[prost(enumeration="ActionType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Edit {
    #[prost(enumeration="ActionType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="5")]
    pub ops: ::prost::alloc::vec::Vec<Op>,
    #[prost(string, repeated, tag="6")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportEdit {
    #[prost(enumeration="ActionType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="5")]
    pub ops: ::prost::alloc::vec::Vec<Op>,
    #[prost(string, repeated, tag="6")]
    pub authors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="7")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub transaction_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Op {
    #[prost(enumeration="OpType", tag="1")]
    pub r#type: i32,
    #[prost(message, optional, tag="2")]
    pub triple: ::core::option::Option<Triple>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Triple {
    #[prost(string, tag="1")]
    pub entity: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub attribute: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub value: ::core::option::Option<Value>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(enumeration="ValueType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Import {
    #[prost(enumeration="ActionType", tag="1")]
    pub r#type: i32,
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub previous_network: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub previous_contract_address: ::prost::alloc::string::String,
    /// repeated Edit edits = 3;
    #[prost(string, repeated, tag="5")]
    pub edits: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Options {
    #[prost(string, tag="1")]
    pub format: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub crop: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpType {
    DefaultOpType = 0,
    SetTriple = 1,
    DeleteTriple = 2,
}
impl OpType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            OpType::DefaultOpType => "DEFAULT_OP_TYPE",
            OpType::SetTriple => "SET_TRIPLE",
            OpType::DeleteTriple => "DELETE_TRIPLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT_OP_TYPE" => Some(Self::DefaultOpType),
            "SET_TRIPLE" => Some(Self::SetTriple),
            "DELETE_TRIPLE" => Some(Self::DeleteTriple),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ValueType {
    DefaultValueType = 0,
    Text = 1,
    Number = 2,
    Entity = 3,
    Uri = 4,
    Checkbox = 5,
    Time = 6,
    GeoLocation = 7,
}
impl ValueType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ValueType::DefaultValueType => "DEFAULT_VALUE_TYPE",
            ValueType::Text => "TEXT",
            ValueType::Number => "NUMBER",
            ValueType::Entity => "ENTITY",
            ValueType::Uri => "URI",
            ValueType::Checkbox => "CHECKBOX",
            ValueType::Time => "TIME",
            ValueType::GeoLocation => "GEO_LOCATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT_VALUE_TYPE" => Some(Self::DefaultValueType),
            "TEXT" => Some(Self::Text),
            "NUMBER" => Some(Self::Number),
            "ENTITY" => Some(Self::Entity),
            "URI" => Some(Self::Uri),
            "CHECKBOX" => Some(Self::Checkbox),
            "TIME" => Some(Self::Time),
            "GEO_LOCATION" => Some(Self::GeoLocation),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActionType {
    DefaultActionType = 0,
    AddEdit = 1,
    ImportSpace = 2,
    AddSubspace = 3,
    RemoveSubspace = 4,
    AddEditor = 5,
    RemoveEditor = 6,
    AddMember = 7,
    RemoveMember = 8,
}
impl ActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ActionType::DefaultActionType => "DEFAULT_ACTION_TYPE",
            ActionType::AddEdit => "ADD_EDIT",
            ActionType::ImportSpace => "IMPORT_SPACE",
            ActionType::AddSubspace => "ADD_SUBSPACE",
            ActionType::RemoveSubspace => "REMOVE_SUBSPACE",
            ActionType::AddEditor => "ADD_EDITOR",
            ActionType::RemoveEditor => "REMOVE_EDITOR",
            ActionType::AddMember => "ADD_MEMBER",
            ActionType::RemoveMember => "REMOVE_MEMBER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT_ACTION_TYPE" => Some(Self::DefaultActionType),
            "ADD_EDIT" => Some(Self::AddEdit),
            "IMPORT_SPACE" => Some(Self::ImportSpace),
            "ADD_SUBSPACE" => Some(Self::AddSubspace),
            "REMOVE_SUBSPACE" => Some(Self::RemoveSubspace),
            "ADD_EDITOR" => Some(Self::AddEditor),
            "REMOVE_EDITOR" => Some(Self::RemoveEditor),
            "ADD_MEMBER" => Some(Self::AddMember),
            "REMOVE_MEMBER" => Some(Self::RemoveMember),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
